### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by kequach** [UtrechtUniversity/uucls#5]
Hello, first of all thanks for providing the template. I read your disclaimer and also noticed that there is no license attached to this repository. Did you think about which one might be a good fit? Otherwise, technically reuse of the materials is never possible. If you like I can look into what might be a good license for this repository.

**Comment by jkorb** [comment]
Hi @kequach ! Thanks for raising this issue and sorry for the slow reply. I'm happy to see that people are interested in the template :) 

RE the license issue: That's a very good point and has been on my internal to do list for a while. I'm all for licensing stuff under fairly permissive licenses (I like MIT for code). The thing is that I'm completely uncertain about the various legal dimensions here since the tex-code implements a protected university style. I suppose that we'd need to get in touch with the house style people, hear what they have to say and get some sort of internal approval for licensing this one way or the other.

At the moment, I have too much on my stack to take care of this properly. But if you're interested in contributing and researching the related issues, that'd be fantastic!

**Comment by kequach** [comment]
Thanks for your reply! I will take a look and you will hear back, hopefully in the form a pull request :)

**Comment by jkorb** [comment]
Hi @kequach ! Any updates on this? I'm doing some work on the class and this would be a great time to add a license..

**Comment by kequach** [comment]
Hi @jkorb, apologies for not answering. I'll talk to Jonathan and will get back to you as soon as possible.

**Comment by kequach** [comment]
Hi @jkorb, I added a pull request with the license that was chosen. This was discussed together with the relevant parties at UU. If I can help out with anything else, please feel free to reach out anytime and again apologies for the delay.

**Comment by jkorb** [comment]
Fantastic, thanks so much! I'll check it out asap. And absolutely no need to apologize: we're all doing this on a voluntary basis, and your help is greatly appreciated :)
